# Generated by Django 4.0.3 on 2022-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegomesa',
            old_name='numeroguia',
            new_name='numero_de_guia',
        ),
        migrations.RenameField(
            model_name='libros',
            old_name='numeroguia',
            new_name='numero_de_guia',
        ),
        migrations.AlterField(
            model_name='juegomesa',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
