# Generated by Django 4.0.2 on 2022-05-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0003_libros_imagen_libros_sinopsis_libros_subido_web'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='sinopsis',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='subido_web',
        ),
    ]
