# Generated by Django 4.0.2 on 2022-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0004_remove_libros_imagen_remove_libros_sinopsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros',
            name='sinopsis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
