# Generated by Django 4.0.2 on 2022-05-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega', '0005_libros_imagen_libros_sinopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imageneslibros'),
        ),
    ]
